name: Build and run Tests

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Install dependencies
      run: dotnet restore
        
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Install Playwright browsers
      run: |
        dotnet tool install --global Microsoft.Playwright.CLI
        playwright install

        
    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal
      env:
        ZARINPAL_MERCHANT_ID: ${{ secrets.ZARINPAL_MERCHANT_ID }}
